import { createContext, useState } from "react";

export const ProductContext = createContext();
export function ProductProvider({ children }) {
  const [products, setProducts] = useState([
    {
      id: 1,
      name: "شامپو بدن شون مدل Strawberry And Milk",
      sku: "P001",
      price: 189000,
      stock: 25,
      isActive: true,
      categoryId: 9,
      brandId: 1,
    },
    {
      id: 2,
      name: "کرم مرطوب‌کننده ویتالیر مدل آبرسان قوی",
      sku: "P002",
      price: 250000,
      stock: 12,
      isActive: true,
      categoryId: 5,
      brandId: 3,
    },
    {
      id: 3,
      name: "ژل شستشو صورت لافارر پوست چرب مدل لایه‌بردار",
      sku: "P003",
      price: 145000,
      stock: 0,
      isActive: false,
      categoryId: 4,
      brandId: 2,
    },
    {
      id: 4,
      name: "شامپو بدن مای مدل Aloe Vera",
      sku: "P004",
      price: 120000,
      stock: 30,
      isActive: true,
      categoryId: 9,
      brandId: 4,
    },
    {
      id: 5,
      name: "کرم مرطوب‌کننده سی گل مدل پوست خشک",
      sku: "P005",
      price: 135000,
      stock: 18,
      isActive: true,
      categoryId: 5,
      brandId: 5,
    },
    {
      id: 6,
      name: "شامپو بدن آردن مدل ضد خشکی",
      sku: "P006",
      price: 160000,
      stock: 9,
      isActive: true,
      categoryId: 9,
      brandId: 6,
    },
    {
      id: 7,
      name: "ژل شستشو صورت هیدرودرم پوست حساس",
      sku: "P007",
      price: 175000,
      stock: 14,
      isActive: true,
      categoryId: 4,
      brandId: 7,
    },
    {
      id: 8,
      name: "کرم ضد جوش درماتیپیک",
      sku: "P008",
      price: 220000,
      stock: 6,
      isActive: true,
      categoryId: 16,
      brandId: 8,
    },
    {
      id: 9,
      name: "شامپو بدن ژوت مدل Fresh",
      sku: "P009",
      price: 110000,
      stock: 22,
      isActive: true,
      categoryId: 9,
      brandId: 9,
    },
    {
      id: 10,
      name: "کرم مرطوب‌کننده پرودرما مدل قوی",
      sku: "P010",
      price: 198000,
      stock: 11,
      isActive: true,
      categoryId: 5,
      brandId: 10,
    },
    {
      id: 11,
      name: "شامپو مو نئودرم ضد ریزش",
      sku: "P011",
      price: 210000,
      stock: 17,
      isActive: true,
      categoryId: 12,
      brandId: 11,
    },
    {
      id: 12,
      name: "سرم پوست ویتالیر ویتامین C",
      sku: "P012",
      price: 320000,
      stock: 8,
      isActive: true,
      categoryId: 8,
      brandId: 3,
    },
    {
      id: 13,
      name: "شامپو بدن بایودرما مدل پوست حساس",
      sku: "P013",
      price: 480000,
      stock: 5,
      isActive: true,
      categoryId: 9,
      brandId: 13,
    },
    {
      id: 14,
      name: "ژل شستشو صورت لاروش پوزای",
      sku: "P014",
      price: 550000,
      stock: 4,
      isActive: true,
      categoryId: 4,
      brandId: 15,
    },
    {
      id: 15,
      name: "کرم مرطوب‌کننده نیوآ کلاسیک",
      sku: "P015",
      price: 98000,
      stock: 40,
      isActive: true,
      categoryId: 5,
      brandId: 18,
    },
    {
      id: 16,
      name: "شامپو بدن داو مدل Nourishing",
      sku: "P016",
      price: 150000,
      stock: 27,
      isActive: true,
      categoryId: 9,
      brandId: 21,
    },
    {
      id: 17,
      name: "ماسک صورت سینره آبرسان",
      sku: "P017",
      price: 165000,
      stock: 19,
      isActive: true,
      categoryId: 7,
      brandId: 25,
    },
    {
      id: 18,
      name: "اسکراب بدن کامان",
      sku: "P018",
      price: 140000,
      stock: 13,
      isActive: true,
      categoryId: 20,
      brandId: 26,
    },
    {
      id: 19,
      name: "شامپو مو پنتن ضد آسیب",
      sku: "P019",
      price: 185000,
      stock: 21,
      isActive: true,
      categoryId: 12,
      brandId: 22,
    },
    {
      id: 20,
      name: "کرم دور چشم اوریاژ",
      sku: "P020",
      price: 390000,
      stock: 7,
      isActive: true,
      categoryId: 24,
      brandId: 24,
    },
    {
      id: 21,
      name: "لوسیون بدن شون مدل Hydrating",
      sku: "P021",
      price: 170000,
      stock: 16,
      isActive: true,
      categoryId: 21,
      brandId: 1,
    },
    {
      id: 22,
      name: "دئودورانت نیوآ مردانه",
      sku: "P022",
      price: 125000,
      stock: 28,
      isActive: true,
      categoryId: 19,
      brandId: 18,
    },
    {
      id: 23,
      name: "شامپو ضد ریزش مو لافارر",
      sku: "P023",
      price: 240000,
      stock: 10,
      isActive: true,
      categoryId: 27,
      brandId: 2,
    },
    {
      id: 24,
      name: "تونر صورت ویتالیر",
      sku: "P024",
      price: 210000,
      stock: 14,
      isActive: true,
      categoryId: 22,
      brandId: 3,
    },
    {
      id: 25,
      name: "ماسک مو هیدرودرم ترمیم‌کننده",
      sku: "P025",
      price: 195000,
      stock: 9,
      isActive: true,
      categoryId: 13,
      brandId: 7,
    },
    {
      id: 26,
      name: "شامپو بدن هیمالیا مدل Herbal",
      sku: "P026",
      price: 135000,
      stock: 20,
      isActive: true,
      categoryId: 9,
      brandId: 30,
    },
    {
      id: 27,
      name: "کرم روشن‌کننده پوست لافارر",
      sku: "P027",
      price: 260000,
      stock: 6,
      isActive: false,
      categoryId: 17,
      brandId: 2,
    },
    {
      id: 28,
      name: "شامپو مو آردن ضد شوره",
      sku: "P028",
      price: 155000,
      stock: 18,
      isActive: true,
      categoryId: 12,
      brandId: 6,
    },
    {
      id: 29,
      name: "ژل شستشو صورت سینره",
      sku: "P029",
      price: 170000,
      stock: 15,
      isActive: true,
      categoryId: 4,
      brandId: 25,
    },
    {
      id: 30,
      name: "کرم مرطوب‌کننده کامان",
      sku: "P030",
      price: 145000,
      stock: 23,
      isActive: true,
      categoryId: 5,
      brandId: 26,
    },
  ]);
  return (
    <ProductContext.Provider value={{ products, setProducts }}>
      {children}
    </ProductContext.Provider>
  );
}
